fixed missing SolvingError import
>>> from pycoin.tx.pay_to import ScriptUnknown
>>> script = ScriptUnknown('abc')
>>> script.solve()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pycoin/tx/pay_to/ScriptUnknown.py", line 16, in solve
    raise SolvingError("unknown script type")
NameError: global name 'SolvingError' is not defined

Imported inside ScriptUnknown.solve() method due to possible infinite import loop